name: Build Dropbear armv7 musl static

on:
  push:
    branches: [ patch-1 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget bzip2 make

      - name: Download musl-cross toolchain
        run: |
          wget https://musl.cc/armv7l-linux-musleabihf-cross.tgz
          tar -xzf armv7l-linux-musleabihf-cross.tgz

      - name: Build dropbear
        run: |
          chmod +x build_arm7.sh
          ./build_arm7.sh

      - name: Upload dropbear artifact
        uses: actions/upload-artifact@v4
        with:
          name: dropbear-armv7-musl-static
          path: output/dropbear
          retention-days: 7
